# Generated by Django 4.2.5 on 2023-10-24 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True, verbose_name='Имя')),
                ('desctiption', models.TextField(blank=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Категоря',
                'verbose_name_plural': 'Категория',
            },
        ),
    ]
